### ISSUE TITLE
[Bug]: block_rotate旋转红石元件后不更新红石邻接表

### ISSUE THREAD

**Issue by kuangby** [CoralFans-Dev/CoralFans#11]
### Describe the bug

对着红石原件使用block_rotate后不更新其输入方向与输出方向。特别的，对于侦测器，只改变观察的方向，不改变信号输出的方向。

### To Reproduce

1、放置一个侦测器，侦测器的输出方向放置一个猪灵头颅
2、对着侦测器使用仙人掌，将侦测器检测的方向修改为猪灵头颅方向
3、打掉并重新放置猪灵头颅
4、观察到侦测器与猪灵头颅产生高频

### Expected behavior

侦测器信号输出方向与放置方向相同

### Platform

win11

### BDS Version

1.21.2

### LeviLamina Version

0.13.5

### Version

0.0.1

**Comment by odorajbotoj** [comment]
fixed
